"""add is_summary column

Revision ID: 38b31c09a0f4
Revises: fb2614295ed5
Create Date: 2025-12-29 15:05:31.908963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b31c09a0f4'
down_revision: Union[str, Sequence[str], None] = 'fb2614295ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_sources', sa.Column('is_summary', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_sources', 'is_summary')
    # ### end Alembic commands ###
