"""create table sectors

Revision ID: 9443072815d5
Revises: da99bded7240
Create Date: 2026-02-09 12:58:44.007491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9443072815d5'
down_revision: Union[str, Sequence[str], None] = 'da99bded7240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actives_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actives_id'], ['actives.id'], ),
    sa.PrimaryKeyConstraint('id', 'actives_id')
    )
    op.create_index(op.f('ix_sectors_actives_id'), 'sectors', ['actives_id'], unique=False)
    op.add_column('news_source_settings', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False))
    op.add_column('news_source_settings', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('news_source_settings', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))

    op.execute(f"""
            CREATE TRIGGER trg_sectors_updated_at
            BEFORE UPDATE ON sectors
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_source_settings', 'deleted_at')
    op.drop_column('news_source_settings', 'updated_at')
    op.drop_column('news_source_settings', 'created_at')
    op.drop_index(op.f('ix_sectors_actives_id'), table_name='sectors')
    op.execute(
            f"DROP TRIGGER IF EXISTS trg_sectors_updated_at ON sectors;"
        )
    op.drop_table('sectors')
    # ### end Alembic commands ###
