"""alter table news about type to jsonb and alter table actives add column is equaity

Revision ID: da99bded7240
Revises: 85c10710ec4d
Create Date: 2026-01-29 12:35:42.968124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da99bded7240'
down_revision: Union[str, Sequence[str], None] = '85c10710ec4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actives', sa.Column('is_equity', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_index(op.f('ix_change_reasons_news_id'), table_name='change_reasons')
    op.alter_column('news', 'about',
               type_=postgresql.JSONB(),
               postgresql_using="about::jsonb",
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column(
        'actives',
        'is_equity',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'about',
               existing_type=postgresql.JSONB(),
               type_=sa.TEXT(),
               postgresql_using="about::jsonb",
               nullable=True)
    op.create_index(op.f('ix_change_reasons_news_id'), 'change_reasons', ['news_id'], unique=False)
    op.drop_column('actives', 'is_equity')
    # ### end Alembic commands ###
