"""create initial tables

Revision ID: fb2614295ed5
Revises: 
Create Date: 2025-12-29 14:33:15.061969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2614295ed5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_cripto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('source_link', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('source_link')
    )
    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_id', sa.Integer(), nullable=False),
    sa.Column('active_value', sa.Float(), nullable=False),
    sa.Column('active_value_prev', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_id'], ['actives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changes_active_id'), 'changes', ['active_id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_datetime'), 'news', ['datetime'], unique=False)
    op.create_index(op.f('ix_news_source_id'), 'news', ['source_id'], unique=False)
    op.create_table('change_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_id', sa.Integer(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('porcent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_id'], ['actives.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_reasons_active_id'), 'change_reasons', ['active_id'], unique=False)
    op.create_index(op.f('ix_change_reasons_change_id'), 'change_reasons', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_reasons_news_id'), 'change_reasons', ['news_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_reasons_news_id'), table_name='change_reasons')
    op.drop_index(op.f('ix_change_reasons_change_id'), table_name='change_reasons')
    op.drop_index(op.f('ix_change_reasons_active_id'), table_name='change_reasons')
    op.drop_table('change_reasons')
    op.drop_index(op.f('ix_news_source_id'), table_name='news')
    op.drop_index(op.f('ix_news_datetime'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_changes_active_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_table('news_sources')
    op.drop_table('actives')
    # ### end Alembic commands ###
